"use strict";
(() => {
    const addNumber = (a, b) => a + b;
    const greet = (name) => `Hello ${name}`;
    const saveTheWorld = () => `Save the world`;
    let myFunction;
    let otherFunction;
    let otherFunctionTwo;
    // myFunction = 10;
    myFunction = addNumber;
    myFunction(1, 2);
    myFunction = greet;
    myFunction('Alejandro');
    myFunction = saveTheWorld;
    myFunction();
    otherFunction = addNumber;
    otherFunction(1, 2);
    otherFunctionTwo = greet;
    otherFunctionTwo('Alejandro');
})();
